// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBof_JPDEEr3rVIjWnzG259rVFvaRjkI9I',
    appId: '1:157803389321:web:417f7256deb5889fc0c158',
    messagingSenderId: '157803389321',
    projectId: 'poliai-f2a8e',
    authDomain: 'poliai-f2a8e.firebaseapp.com',
    storageBucket: 'poliai-f2a8e.firebasestorage.app',
    measurementId: 'G-KGJVH2CDEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCSrUfP6VN4lwxj794xBk9xElQtQnNzkU',
    appId: '1:157803389321:android:12f7ce9f06f6c7a2c0c158',
    messagingSenderId: '157803389321',
    projectId: 'poliai-f2a8e',
    storageBucket: 'poliai-f2a8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLKE2DJZ1gBfyknPo0eBIupnRZ9vdNJdk',
    appId: '1:157803389321:ios:5cc03b0d11ed4068c0c158',
    messagingSenderId: '157803389321',
    projectId: 'poliai-f2a8e',
    storageBucket: 'poliai-f2a8e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBof_JPDEEr3rVIjWnzG259rVFvaRjkI9I',
    appId: '1:157803389321:web:75b87b30a0a3fb1cc0c158',
    messagingSenderId: '157803389321',
    projectId: 'poliai-f2a8e',
    authDomain: 'poliai-f2a8e.firebaseapp.com',
    storageBucket: 'poliai-f2a8e.firebasestorage.app',
    measurementId: 'G-XPYEXN20J8',
  );

}